name: Java CI

on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Validate, build and run tests
      run: mvn --batch-mode --update-snapshots verify
    - name: Create javadoc -f pom.xml
      run: mvn javadoc:javadoc
    - name: Create jar file
      run: mvn jar:jar -f pom.xml
