name: Java - Documentation
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  java-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Cleanup previous build.
        run: rm -rf ./docs/
      - name: Create javadoc.
        run: |
          mvn javadoc:javadoc
          mv ./target/site/apidocs/ ./docs/
          mvn clean
      - name: Commit javadoc.
        run: |
          git add ./docs --force
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "[skip ci] Autogenerate Javadoc."
          git push origin HEAD:main
