name: Version - minor
on:
  push:
    branches: [ main ]

jobs:
  minor-tag-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump minor version of tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
  minor-pom-bump:
    needs: [ minor-tag-bump ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Get Previous tag
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Bump minor version of pom
        run: |
          mvn -B versions:set -DnewVersion=${{ steps.previous_tag.outputs.tag }} -DgenerateBackupPoms=false
      - name: Commit and push
        run: |
          git pull origin main
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "[skip ci] Bump minor version"
          git push origin HEAD:main
